"""Add topic to discussion posts

Revision ID: 32d13d51fce1
Revises: 5b9e136842e3
Create Date: 2026-03-18 18:19:45.809124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d13d51fce1'
down_revision = '5b9e136842e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion_post', schema=None) as batch_op:
        batch_op.drop_column('topic')

    # ### end Alembic commands ###
