"""Add descriptions and assignment file

Revision ID: 33044eaa733e
Revises: aa6599667eba
Create Date: 2026-03-18 15:27:01.771100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33044eaa733e'
down_revision = 'aa6599667eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('live_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('live_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
