"""Add descriptions

Revision ID: 54c5d360c588
Revises: 0b3350c6bf87
Create Date: 2026-03-18 13:48:37.413589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c5d360c588'
down_revision = '0b3350c6bf87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('recorded_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recorded_class', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
