"""Add school_name and update course defaults

Revision ID: 5b9e136842e3
Revises: 33044eaa733e
Create Date: 2026-03-18 17:24:21.419360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b9e136842e3'
down_revision = '33044eaa733e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('credit_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('instructor', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('instructor')
        batch_op.drop_column('credit_points')
        batch_op.drop_column('school_name')

    # ### end Alembic commands ###
