"""Add live_description to Course

Revision ID: 9c2a1af65368
Revises: 54c5d360c588
Create Date: 2026-03-18 14:43:20.333003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2a1af65368'
down_revision = '54c5d360c588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('live_description', sa.Text(), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('recorded_class', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recorded_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('live_description')

    # ### end Alembic commands ###
